@baseUrl = http://localhost:3000

### Hello
GET {{baseUrl}}/

### Create loan
POST {{baseUrl}}/loans
Content-Type: application/json

{
  "amount": 5000,
  "termMonths": 12
}

### List loans
GET {{baseUrl}}

### Get one loan
GET {{baseUrl}}/loans/1
