@baseUrl = http://localhost:3000

### Hello
GET {{baseUrl}}/

### Create user
# @name createUser
POST {{baseUrl}}/users/create
Content-Type: application/json

{
  "name": "Mohamed Fathy",
  "email": "mohamed.fathy@example.com",
  "password": "23213213213",
  "phoneNumber": "+971501234567",
  "role": "admin"
}

### Get the user created above
GET {{baseUrl}}/users/18771e51-1b42-45c2-9d98-03c3a5353c45

### list users
GET {{baseUrl}}/users/list
Content-Type: application/json


